return
{
    configurationEnableWindow = false,
    enable = true,

    allPlayersEnableWindow = false,
    allHideWhenMenu = true,
    allHideWhenSymbolChat = true,
    allHideWhenMenuUnavailable = true,
    allPlayersChanged = false,
    allPlayersAnchor = 1,
    allPlayersX = 50,
    allPlayersY = 50,
    allPlayersW = 450,
    allPlayersH = 350,
    allPlayersNoTitleBar = "NoTitleBar",
    allPlayersNoResize = "",
    allPlayersNoMove = "",
    allPlayersTransparentWindow = true,
    allPlayersListHorizontal = true,
    allPlayersListMaxLength = 4,
    allPlayersShowIndex = true,
    allPlayersShowName = true,
    allPlayersShowHpBar = true,
    allPlayersShowBuff = true,

    singlePlayersEnableWindow = true,
    singlePlayersShowBarText = true,
    singlePlayersShowBarMaxValue = true,
    singlePlayersBalancingHorizontalPosition = false,

    players = {
        {
            EnableWindow = true,
            HideWhenMenu = true, 
            HideWhenSymbolChat = true, 
            HideWhenMenuUnavailable = nil, 
            ShowName = true,
            ShowHPBar = true,
            SD = true,
            Invulnerability = true,
            Changed = false,
            Anchor = 3,
            X = 350,
            Y = -100,
            W = 150,
            H = 98,
            NoTitleBar = "NoTitleBar",
            NoResize = "NoResize",
            NoMove = "NoMove",
            NoScrollbar = "NoScrollbar",
            AlwaysAutoResize = "AlwaysAutoResize",
            TransparentWindow = false,
        },
        {
            EnableWindow = true,
            HideWhenMenu = true, 
            HideWhenSymbolChat = true, 
            HideWhenMenuUnavailable = nil, 
            ShowName = true,
            ShowHPBar = true,
            SD = true,
            Invulnerability = true,
            Changed = true,
            Anchor = 3,
            X = 500,
            Y = -100,
            W = 150,
            H = 28,
            NoTitleBar = "NoTitleBar",
            NoResize = "NoResize",
            NoMove = "NoMove",
            NoScrollbar = "NoScrollbar",
            AlwaysAutoResize = "AlwaysAutoResize",
            TransparentWindow = false,
        },
        {
            EnableWindow = true,
            HideWhenMenu = true, 
            HideWhenSymbolChat = true, 
            HideWhenMenuUnavailable = nil, 
            ShowName = true,
            ShowHPBar = true,
            SD = true,
            Invulnerability = true,
            Changed = true,
            Anchor = 3,
            X = 640,
            Y = -100,
            W = 150,
            H = 28,
            NoTitleBar = "NoTitleBar",
            NoResize = "NoResize",
            NoMove = "NoMove",
            NoScrollbar = "NoScrollbar",
            AlwaysAutoResize = "AlwaysAutoResize",
            TransparentWindow = false,
        },
        {
            EnableWindow = true,
            HideWhenMenu = true, 
            HideWhenSymbolChat = true, 
            HideWhenMenuUnavailable = nil, 
            ShowName = true,
            ShowHPBar = true,
            SD = true,
            Invulnerability = true,
            Changed = true,
            Anchor = 3,
            X = 800,
            Y = -100,
            W = 150,
            H = 28,
            NoTitleBar = "NoTitleBar",
            NoResize = "NoResize",
            NoMove = "NoMove",
            NoScrollbar = "NoScrollbar",
            AlwaysAutoResize = "AlwaysAutoResize",
            TransparentWindow = false,
        },
    },
   myself = {
        EnableWindow = false,
        HideWhenMenu = true,
        HideWhenSymbolChat = true,
        HideWhenMenuUnavailable = true,
        ShowName = true,
        ShowBarText = true,
        ShowBarMaxValue = true,
        ShowHPBar = true,
        SD = true,
        Invulnerability = true,
        Changed = false,
        Anchor = 3,
        X = 5,
        Y = -5,
        W = -150,
        H = 98,
        NoTitleBar = "NoTitleBar",
        NoResize = "NoResize",
        NoMove = "NoMove",
        NoScrollbar = "NoScrollbar",
        AlwaysAutoResize = "AlwaysAutoResize",
        TransparentWindow = false,
   },
}
